package cn.deepclue.scheduler;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'magneto' at '17-7-11 下午2:14' with Gradle 3.5
 *
 * @author magneto, @date 17-7-11 下午2:14
 */
public class SchedulerService {
    private static Logger logger = LoggerFactory.getLogger(SchedulerService.class);

    private JobService service;

    public void start() {
        service.start();
    }

    public void shutdown() {
        service.shutdown();
    }

    public void setService(JobService service) {
        this.service = service;
    }

    public static void main(String[] args) {
        SchedulerService schedulerService = new SchedulerService();

        //TODO bind a concrete schedule

        try {
            schedulerService.start();
        } catch (Exception e) {
            logger.error(e.getMessage(), e);
        } finally {
            schedulerService.shutdown();
        }
    }
}
