/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'magneto' at '17-7-11 下午2:14' with Gradle 2.12
 *
 * @author magneto, @date 17-7-11 下午2:14
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
