/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'magneto' at '17-7-11 下午2:14' with Gradle 3.5
 *
 * @author magneto, @date 17-7-11 下午2:14
 */
public class SchedulerService {
    public static void start(){}

    public static void main(String[] args) {
        start();
    }
}
